[package]
name = "rsfetch-async"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nixinfo-async = { path = "../nixinfo-async" }
tokio = { version = "1.13.0", features = ["full"] }
